In [73]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [74]:
df = pd.read_csv('backend\database\MVP_DB_V2_NY_CA.csv')

In [75]:
df.head(2)

,Incentive Name,Website Link,State,County,Jurisdiction,Provider,Incentive Type,Technology,Sub-Technology,Product,Product Capacity,Product Eligibility,Incentive Amount,Unit,Incentive Value,Estimated Incentive Value,Application/Eligibility Link,Assumption Type,Assumed Capacity
0,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,HVAC,HVAC,HVAC Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN
1,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,LED Lighting,LED Lighting,LED Lighting Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN

In [76]:
userState = "NY"
userCountry = 'USA'
userCounty = "NEW YORK CITY"

In [77]:
rebateData = df.copy()
fiteredRebateData = rebateData[ (rebateData["State"] == userCountry) | \
                                ((rebateData["State"] == userState) & (rebateData["County"] == userState)) | \
                                (rebateData["County"] == userCounty)]

In [78]:
fiteredRebateData.head(2)

,Incentive Name,Website Link,State,County,Jurisdiction,Provider,Incentive Type,Technology,Sub-Technology,Product,Product Capacity,Product Eligibility,Incentive Amount,Unit,Incentive Value,Estimated Incentive Value,Application/Eligibility Link,Assumption Type,Assumed Capacity
0,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,HVAC,HVAC,HVAC Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN
1,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,LED Lighting,LED Lighting,LED Lighting Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN

In [79]:
fiteredRebateData['Estimated Incentive Value'] = fiteredRebateData['Estimated Incentive Value'].astype(float)

C:\Users\siddh\AppData\Local\Temp\ipykernel_6708\1928463470.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fiteredRebateData['Estimated Incentive Value'] = fiteredRebateData['Estimated Incentive Value'].astype(float)

In [80]:
resdf = df.copy()
resdf.head(3)

,Incentive Name,Website Link,State,County,Jurisdiction,Provider,Incentive Type,Technology,Sub-Technology,Product,Product Capacity,Product Eligibility,Incentive Amount,Unit,Incentive Value,Estimated Incentive Value,Application/Eligibility Link,Assumption Type,Assumed Capacity
0,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,HVAC,HVAC,HVAC Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN
1,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,LED Lighting,LED Lighting,LED Lighting Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN
2,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,Insulation,Insulation,Insulation Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,NaN,2820.0,2820.0,Link,NaN,NaN

In [81]:
INSULATION_SO_EUI = 0.9
buildingArea = 1500
INSULATION_BREAKUP = {
    "Envelope" : 0.8,
    "Pipe": 0.2,
}
THERM_FACTOR = 0.0341296

In [82]:
resdf["Amt_Estimation"] = np.where(
                    resdf["Assumption Type"] == "Insulation Type 2",
                    buildingArea * resdf["Incentive Value"],
                    resdf["Incentive Value"])

In [83]:
resdf[resdf["Assumption Type"] == "Insulation Type 2"]

,Incentive Name,Website Link,State,County,Jurisdiction,Provider,Incentive Type,Technology,Sub-Technology,Product,Product Capacity,Product Eligibility,Incentive Amount,Unit,Incentive Value,Estimated Incentive Value,Application/Eligibility Link,Assumption Type,Assumed Capacity,Amt_Estimation
232,Commercial and Industrial Energy Efficiency Pr...,Link,NY,NY,Utility,ConEd,Discount,Insulation,Envelope,Window Film,Variable Capacities,NaN,$1/sqft,NaN,1.00,1500.0,Link,Insulation Type 2,NaN,1500.0
233,Commercial and Industrial Energy Efficiency Pr...,Link,NY,NY,Utility,ConEd,Discount,Insulation,Envelope,Cool Roof,Variable Capacities,NaN,$50/1000 sqft,NaN,0.05,75.0,Link,Insulation Type 2,NaN,75.0

In [9]:
rebates_data = fiteredRebateData[fiteredRebateData['Incentive Type'] == 'Discount']
tax_amount_data = fiteredRebateData[fiteredRebateData['Incentive Value'] != 'Discount']

In [10]:
fiteredRebateData.columns

Index(['Incentive Name', 'Website Link', 'State', 'County', 'Jurisdiction',
       'Provider', 'Incentive Type', 'Technology', 'Sub-Technology', 'Product',
       'Product Capacity', 'Product Eligibility', 'Incentive Amount',
       'Incentive Value', 'Estimated Incentive Value',
       'Application/Eligibility Link', 'Assumption Type', 'Assumed Capacity'],
      dtype='object')

In [11]:
resdf_rebate = rebates_data.groupby(['Technology' ])['Estimated Incentive Value'].agg(['mean'])
resdf_rebate

                      mean
Technology
Controls        445.083333
Custom Program  769.675000
HVAC            906.213538
Insulation      547.291429
LED Lighting    442.982573
Solar                  NaN

In [12]:
resdf_tax = tax_amount_data.groupby(['Technology' , 'Sub-Technology'])['Estimated Incentive Value'].agg(['mean'])
resdf_tax

                                          mean
Technology     Sub-Technology
Controls       Building Controls    445.083333
               Controls           10000.000000
Custom Program Lighting             189.000000
               Whole Building      1350.350000
HVAC           Air Compressor      1679.688333
               Air Conditioners     585.092143
               HVAC                6410.000000
               HVAC Controls        159.100000
               Heat Pump           2655.716000
               Heaters              120.637500
               Pumps & Motors       492.278846
Insulation     Envelope             760.950000
               Insulation          6410.000000
               Pipe                 262.413333
LED Lighting   Downlights           529.307692
               Exterior             388.938462
               Interior             518.201709
               LED Controls          77.135294
               LED Lighting        6410.000000
               Lamps                437.065714
               Troffers             344.971429
Solar          Solar              10000.000000
               Storage                     NaN

In [14]:
result = []
for name,tech, group in resdf_tax:
    group_dict = group.to_dict(orient='records')
    result.append({name: group_dict})

# Convert the result list to JSON
json_result = json.dumps(result, indent=2)
json_result

ValueError: too many values to unpack (expected 3)

In [114]:
resdf2 = fiteredRebateData.groupby(['Technology' , 'Sub-Technology','Incentive Name','Provider', 'Incentive Type'])[['Estimated Incentive Value']].agg(['mean'])

In [125]:
resdf2 = rebates_data.groupby(['Technology' ,'Incentive Name','Provider'])[['Estimated Incentive Value']].agg(['mean']).reset_index()
resdf2[resdf2["Technology"] == 'Controls']

,Technology,Incentive Name,Provider,Estimated Incentive Value
,,,,mean
0,Controls,Central Air Conditioner program,Central Hudson,200.0
1,Controls,Commercial and Industrial Energy Efficiency Pr...,ConEd,607.5
2,Controls,NYSERDA - Real Time Energy Management Program,NYSERDA,NaN
3,Controls,Real Time Energy Management (RTEM) Incentive,National Grid,40.5

In [96]:
fiteredRebateData.head(2)

,Incentive Name,Website Link,State,County,Jurisdiction,Provider,Incentive Type,Technology,Sub-Technology,Product,Product Capacity,Product Eligibility,Incentive Amount,Incentive Value,Estimated Incentive Value,Application/Eligibility Link,Assumption Type,Assumed Capacity
0,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,HVAC,HVAC,HVAC Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,"2,820.00",2820.0,Link,NaN,NaN
1,179D Commercial Buildings Energy-Efficiency Ta...,Link,USA,USA,Federal,IRS,Tax Deduction,LED Lighting,LED Lighting,LED Lighting Upgrades,NaN,NaN,Incentives starting at $1.88/sqft and going up...,"2,820.00",2820.0,Link,NaN,NaN

In [97]:
fiteredRebateData.columns

Index(['Incentive Name', 'Website Link', 'State', 'County', 'Jurisdiction',
       'Provider', 'Incentive Type', 'Technology', 'Sub-Technology', 'Product',
       'Product Capacity', 'Product Eligibility', 'Incentive Amount',
       'Incentive Value', 'Estimated Incentive Value',
       'Application/Eligibility Link', 'Assumption Type', 'Assumed Capacity'],
      dtype='object')

In [98]:
fiteredRebateData[['Product','Product Capacity', 'Product Eligibility', 'Incentive Amount','Application/Eligibility Link']].iloc[15:19]

,Product,Product Capacity,Product Eligibility,Incentive Amount,Application/Eligibility Link
15,Heat Pump Water Heater,Tank Capacity: <120 gallons,NEEP certified,$700/unit,Link
16,Heat Pump - GSHP Desuperheater,Variable Capacities,NEEP certified,$100/unit,Link
17,Custom Space Heating plus Envelope,Variable Capacities,NEEP certified,$70 - $80/MMBTU of annual energy savings,Link
18,Heat Pump Water Heater,Tank Capacity: >120 gallons,NEEP certified,$70/MBTU of annual energy savings,Link